### ISSUE TITLE
Other problem with Spanish translation

### ISSUE THREAD

**Issue by Seroluce** [SMUnlimited/AMAI#157]
Hello, some letters in the Spanish translation are displayed incorrectly.
![image](https://github.com/SMUnlimited/AMAI/assets/141604179/24ec2833-ffc3-4bfe-9168-1b9e718a9c1e)

**Comment by Slayer95** [comment]
#142 changed the encodings of many ``Languages/*/Strategy.txt`` files to ``UTF-8``, but they ought to use these encodings: https://github.com/SMUnlimited/AMAI/blob/master/Languages.txt

cc @jzy-chitong56 

This explains the Russian issues. Note also that ``Languages/Spanish/Commander.txt`` is wrongly UTF-8, too.

**Comment by jzy-chitong56** [comment]
It does exist

Perhaps it's my Chinese system, which defaults to UTF8. I use VSCODE or NOT++, TXT conversion, and I don't even know if it was successful

At the same time, due to different encoding, some files cannot be successfully uploaded (I am using the web version GIT and do not understand the client), so I must delete the source files and upload them again

Finally, when using the web version for modification, it will automatically transcode to UTF8

I will try to modify these files, but I cannot guarantee their success
@Slayer95

**Comment by Slayer95** [comment]
Maybe all should just be UTF8 to prevent this kind of issues. @SMUnlimited ?

**Comment by SMUnlimited** [comment]
Good spot Slayer95, probably is better to be utf8 these days anyway, the ISO standard is much older and its owners disbanded in 2004.

**Comment by jzy-chitong56** [comment]
There is a minor issue that is not important
Do you know that Chinese is utf8,When you directly modify the com.ai file,For example, temporary testing, not wanting to touch the source code,All Chinese characters and symbols in the chatXXX file will not be displayed in the game,
If the com.ai file is compiled again,Chinese question marks may be directly lost, resulting in script syntax errors and inability to execute the script
But the text recorded in the strategy file is not affected
only
