### ISSUE TITLE
Localization support for the installer 

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#209]
As we have multiple languages in AMAI would be good to include such in the installer as well.

**Comment by paulo101977** [comment]
> As we have multiple languages in AMAI would be good to include such in the installer as well.

Since the installer uses angular, it supports i18n by itself. The big question is: where will we put a language switch selector? Or will it be possible to get the language automatically from the operating system?

**Comment by jzy-chitong56** [comment]
> > As we have multiple languages in AMAI would be good to include such in the installer as well.
> 
> 
> 
> Since the installer uses angular, it supports i18n by itself. The big question is: where will we put a language switch selector? Or will it be possible to get the language automatically from the operating system?


If I could provide a workflow that can generate applications, I think I could create a Chinese version for Chinese players to use and ask AI how to set up multilingualism

Unfortunately, I don't know how to handle local computer environment installations or set up workflows, so I can only reach out for ready-made ones

**Comment by paulo101977** [comment]
> Okay, I'm exaggerating. I barely generated a Chinese app, but I still gave up on the code
> 
> The menu bar does not directly indicate version support, and it feels like the main interface has been wasted I referenced the old installer and generated a new UI using AXURE, along with the HTML created by AXURE , You can experience the interaction But AXURE used too much .JS, so you may not want to put it in the source code
> 
> Of course, it would be best to provide a version subtitle and balance explanation, but I didn't add it either After operating the button, the pop-up log box will block the button, but the version and command settings are still visible, and you may need to deal with disabling issues

The look was very good. I could use your designer in the installer. I'm also thinking about the possibility of automatically selecting the language for translation. The only problem is whether we will have support with this translation, because the only languages ​​I know are English, Portuguese and Spanish and, as I said, I would just automatically select the language.

Another thing I didn't understand: is there a specific version of AMAI for each version of Warcraft? Because I don't know if I can make this distinction to do a version-directed installation.

For now, I think I'll focus on localization and see if I can at least automate the language selection.

@SMUnlimited  @jzy-chitong56

**Comment by jzy-chitong56** [comment]
https://github.com/jzy-chitong56/Electron/tree/%E4%B8%BB%E9%A1%B5

I have basically finished the front-end, except for some scaling that is not very good, but my core services cannot be called,I won't handle it here anymore

send Unable to call

**Comment by paulo101977** [comment]
> https://github.com/jzy-chitong56/Electron/tree/%E4%B8%BB%E9%A1%B5
> 
> I have basically finished the front-end, except for some scaling that is not very good, but my core services cannot be called,I won't handle it here anymore
> 
> send Unable to call

Let me get this straight: you managed to make the visual changes, but it's not working properly. Would it be this? If so, I can try to run your code and try to understand it here. The problem is that I'm busy at work this week.

**Comment by jzy-chitong56** [comment]
JS cannot run normally, and I have no other options. You can try the HTML in the **src** directory. Because I removed the menu, the F12 console couldn't come out and I couldn't see any errors, so I couldn't determine where the error was. I think you need to add the menu first

I intentionally wrote the styles and elements together to avoid the style files from being packaged. 

Of course, the prerequisite is that you have finished your work

**Comment by paulo101977** [comment]
> JS cannot run normally, and I have no other options. You can try the HTML in the **src** directory. Because I removed the menu, the F12 console couldn't come out and I couldn't see any errors, so I couldn't determine where the error was. I think you need to add the menu first
> 
> I intentionally wrote the styles and elements together to avoid the style files from being packaged.
> 
> Of course, the prerequisite is that you have finished your work

I understood. What you are having is a problem debugging. I'll see if tomorrow afternoon, Brazilian time, I can find some time and take a look at the code.

**Comment by jzy-chitong56** [comment]
https://github.com/jzy-chitong56/Electron/blob/APP%E9%A1%B5

OK，The modification of this branch is more in line with the code structure and is also convenient to set up in multiple languages. However, the front-end is currently unable to trigger it, and `action prompt is not defined`

**Comment by SMUnlimited** [comment]
In the end, stayed with ngx-translate as the automatic and dynamic loading of languages is better than building an installer per language https://github.com/SMUnlimited/AMAI/commit/1db2fc4c35f93f69a14b894d14642b510e05d111
