### ISSUE TITLE
Scores missing from AI's

### ISSUE THREAD

**Issue by SMUnlimited** [SMUnlimited/AMAI#210]
https://www.hiveworkshop.com/threads/advanced-melee-ai.62879/post-3605606

Suspect its todo with AI's sharing unit control on defeat. 

![WC3ScrnShot_122523_133147_000](https://github.com/SMUnlimited/AMAI/assets/5180431/487afa47-2fb4-4142-96c2-fca763adf948)

![WC3ScrnShot_122523_182616_000](https://github.com/SMUnlimited/AMAI/assets/5180431/202d5593-1dad-4e18-8278-0ce1f4776d47)

**Comment by jzy-chitong56** [comment]
The premise is that if this situation really only occurs during sharing
I can only think of this situation

At that time, I noticed this switch while dealing with CREEP units near the tavern that were misjudged  --  **recalculate_heros**

if AI all unit under control , then not unit go to buy   
and if AI use Neutral Heros , This situation may occur
Because the purchase of the hero failed, **recalculate_heros** was not processed in the buy hero  JOB

Players may also think that why AI always manipulates units recklessly and goes against their own control

**Comment by jzy-chitong56** [comment]
It should be noted that player control may conflict with all buy job,Perhaps it is feasible to use cheating modes to help AI complete purchases, or create an uncontrollable unit to replace execution, or tell players that this unit is shopping, please do not control it

**Comment by jzy-chitong56** [comment]
I almost forgot this fix 


```
function CanCreepGuardsSleep takes integer nn returns boolean
  local group g = null
  local unit u = null
  local boolean b = true
  if nearest_neutral[nn] != null and FirstOfGroup(neutral_guards[nn]) != null then
    set g = CopyGroup(neutral_guards[nn],g)
    loop
      set u = FirstOfGroup(g)
      exitwhen u == null
      exitwhen not UnitCanSleep(u)
      call GroupRemoveUnit(g, u)
    endloop
    call DestroyGroup(g)
    set g = null
    set b = (u == null)
    set u = null
  endif
  return b
endfunction
```
