### ISSUE TITLE
InstallToDir.pl printf too much

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#211]
InstallXXXtoDir.pl  printf windows UAC too much

When running, you will know  administrator privileges 
There's no need to print on write every type of file or every map file 

log too long

**The same problem also exists in the installer**

Either report an error at the beginning and terminate install
Either report an error in the end ---  This is better

```
htsize:0
add ai scripts:0
Installing AMAI and Commander to D:\WAR3\Warcraft III - 1.29.2\Maps\x/(24)Emersion v3.0 Standard MeleeX.w3x
htsize:0
add ai scripts:0
Installing AMAI and Commander to D:\WAR3\Warcraft III - 1.29.2\Maps\x/(24)Entangled Forest.w3x
htsize:0
add ai scripts:0
Installing AMAI and Commander to D:\WAR3\Warcraft III - 1.29.2\Maps\x/(24)MadnessInTheBarrens.w3x
htsize:0
add ai scripts:0
Installing AMAI and Commander to D:\WAR3\Warcraft III - 1.29.2\Maps\x/(6)Moonglade.w3x
htsize:0
add ai scripts:0
```

**Comment by SMUnlimited** [comment]
Its fine for the moment, the additional logging is useful due to a number of people still having unknown issues from the install. 

Enhancement to track all maps that error and repeat at the end may be useful but i'll keep the full log for now. It may be all non-zero error codes are a problem, but its not the case for htsize which seems to be valid.

**Comment by jzy-chitong56** [comment]
It would be better if a prompt could pop up at the select directory . Especially for installers

![image](https://github.com/SMUnlimited/AMAI/assets/48715223/e587a2e9-455c-411d-a8fc-80ef59ece770)
