### ISSUE TITLE
C_Attack and C_Greet maybe no need enter the chat sequence

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#217]
C_Attack It's real-time , can help players better cooperate with AI , if attack_done appearing after queuing can also make players 
 feel strange
C_Greet  display only once

**Comment by SMUnlimited** [comment]
That will be terribly noisy with 12 allies as they will all be attacking different things.

Only way to persist real time is if only a few ally players chat run in real time... e.g maybe 6 allies at most. Then can apply same for the greeting. 

Unrelated but spotted another bug due to SetAllianceTarget in team games which modifies AI's target regardless of target passed to attack, it will have sent a chat message with the wrong location or target.
