### ISSUE TITLE
Clean up allies and adjust targets

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#314]
One of the reasons that hinders AI from refreshing attack targets is that allied targets have not been cleared
so you can see that my code has basically synchronized the exit conditions for attacking sleep
I am thinking about another level, such as town threats, retreats, empty attack groups, teleportation, etc., should we also clean up allied targets after events occur?
After all, at this point, AI has already left the battlefield and is still letting allies attack. Do hope that allies can capture the target, or cover retreat, or let them go die?
it seems `GetStoredInteger` can override these logics, but I'm not sure if they're valid

`function ClearAllianceTarget takes unit old returns nothing
  if old == null or not UnitAlive(old) or (UnitInvis(old) and not IsUnitDetected(old, ai_player)) or GetHandleId(old) == GetStoredInteger(amaiCache, Int2Str(ALLIANCE_TARGET), "0") then
    call SetAllianceTargetIfLead(null)
  endif
endfunction`

**Comment by SMUnlimited** [comment]
I don't believe there is an issue here. Currently allied target will be cleared if the unit that was the AI's target matches the alliance target or we directly pass in null. Any AI's already sent to the allied target will continue but others will pick new targets because an AI gave up or the target was successfully killed.  Any AI's attacking something else won't clear the alliance target.

**Comment by jzy-chitong56** [comment]
ok
BUT `IsUnitVisible` Still present in some JOBs

**Comment by jzy-chitong56** [comment]
ok
BUT `IsUnitVisible` Still present in some JOBs
