### ISSUE TITLE
（DEVTOOL）Compilation should pause when RESULTOPTVER is 1

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#353]
when RESULTOPTVER is 1, Compilation should pause
but make all just at last VER pause

https://github.com/jzy-chitong56/AMAI/commit/ab23e6a132510d51ab5ee67bd484a32bb30cb9f6

**Comment by Slayer95** [comment]
Hello. I'm sorry that your workflow has been disturbed by my proposal of removing pauses in the ``.bat`` scripts. However, I still maintain that pauses are generally bad, since it harms composability of scripts.

In fact, you are already able to easily see the output of the scripts by just opening your ``cmd.exe`` prompt, and typing ``MakeAll.bat`` to run it, without risk of the prompt closing. Furthermore, there are additional convenient features brought by using the ``cmd``, such as the capability to write the output of AMAI to a log file, by running ``MakeAll.bat > amai.log 2>&1``.

There are also a few alternatives you can use in order for AMAI compilation to fit your most convenient workflow, such as keeping your own versions of the ``.bat`` files in your fork, or creating ``MakeAllClickable.bat`` files which run ``MakeAll.bat`` but incoporate ``pause`` on the end.

That said, I do think that this latest proposal you bring of pausing only when compilation fails is a reasonable middle-ground, that effectively balances speed and usability for all use cases I can currently foresee. Of course, whether it's ultimately incorporated is up to @SMUnlimited .

**Comment by jzy-chitong56** [comment]
In fact, if a player uses the source code, they usually double-click to run BAT directly and will not use CMD EXE， I've also heard for the first time that this can be done
All my ideas are based on the operation of double clicking to run BAT

**Comment by jzy-chitong56** [comment]
When Perl is not installed, the system will not prompt a failure and will still automatically close the compilation window

Is there a good solution to this?

**Comment by Slayer95** [comment]
> When Perl is not installed, the system will not prompt a failure and will still automatically close the compilation window
> 
> Is there a good solution to this?

In Windows, something like this can be done (untested):
```bat
where perl
if "%errorlevel%"!="0" (
  ECHO Please install Perl as a requirement to compile AMAI.
  pause
  exit /b %errorlevel%
)
; now we can run perl
```

**Comment by Slayer95** [comment]
Adding ``%errorlevel%`` checks after the very first (or every) ``perl`` command in ``MakeVERBase.bat`` could also do the trick.

**Comment by jzy-chitong56** [comment]
where perl
if "%errorlevel%"=="1" SET RESULTMAKEVER=2
like this?

**Comment by Slayer95** [comment]
That's also an option, assuming that RESULTMAKEVER==2 is checked late, of course :)

**Comment by jzy-chitong56** [comment]
https://github.com/jzy-chitong56/AMAI/commit/fb009e07dc4d3cefb70e0b2e41250276a2bafb3a
like this？

**Comment by Slayer95** [comment]
> [jzy-chitong56@fb009e0](https://github.com/jzy-chitong56/AMAI/commit/fb009e07dc4d3cefb70e0b2e41250276a2bafb3a) like this？

Yeah. The ``.bat`` files look good. Please see my comment over there regarding the ``.pl`` files.

**Comment by SMUnlimited** [comment]
Had to tweak this slightly for the strategy manager support and github automation, but working with latest commit.
