### ISSUE TITLE
Blademaster in Wind Walk does not attack

### ISSUE THREAD

**Issue by Slayer95** [SMUnlimited/AMAI#378]
It just hangs around the battle, but it never reveals itself. When WW is over, BM uses it again, and does nothing.

**Comment by paulo101977** [comment]
> It just hangs around the battle, but it never reveals itself. When WW is over, BM uses it again, and does nothing.

Probably because his attack logic is still contained in the game's original AI. Perhaps the only way to do this, I had already discussed, is to train an external AI. However, due to the limitations of the game, unfortunately this will not be possible or it would have to give up a lot of time and resources. I don't know if there is an easy way to hardcode it.

**Comment by Slayer95** [comment]
I'm fairly sure training AI is out of scope. I don't see why hardcoding BM attacking would be hard.

**Comment by edsson-malorne** [comment]
Yes, the sword master is a bit clumsy with his windwalk and sometimes misses opportunities to attack, he spends a lot of time waiting invisible, while his army is killed. I would also like him to have a better refinement in his skills.

**Comment by SMUnlimited** [comment]
Pretty sure this used to work so its become broken at some point. Will check whats happened.

**Comment by Slayer95** [comment]
Still seeing this. Tested with vanilla TFT AMAI on 1.27a.

[scaredybm.zip](https://github.com/user-attachments/files/17178436/scaredybm.zip)

**Comment by SMUnlimited** [comment]
Its intermittent but yes still sometimes blademaster fails to attack out.

**Comment by SMUnlimited** [comment]
Now seems to be working, mainly caused by bug in the jass apis so changed api in use.

**Comment by Slayer95** [comment]
Wow. Thanks!
