### ISSUE TITLE
I believe it's 【about】 button breaking new installer

### ISSUE THREAD

**Issue by jzy-chitong56** [SMUnlimited/AMAI#436]
my code structure and buttons are different
and have other buttons translate

```
        "DEV_TOOL": "DevTools",
        "FULLSCREEN": "FullScreen",
```

https://github.com/jzy-chitong56/Electron/blob/%E6%B5%8B%E8%AF%95%E8%AF%AD%E8%A8%80%E8%BD%AC%E6%8D%A2/src/app/core/services/menu/menu.service.ts

**Comment by SMUnlimited** [comment]
Various issues: one some events never fired for unsupported languages and electron translations didn't have a default so that broke as well. The install commands hadn't been updated for the new event names. Pulled out view panel so developer tools are always accessible even if languages explode again.
